### ISSUE TITLE
TASK_HEADS_PATH in nli_pertask_linearsearch.py

### ISSUE THREAD

**Issue by arghavan-kpm** [gstoica27/KnOTS#2]
Hi, thanks for providing this helpful repo. I was wondering what we should replace the TASK_HEADS_PATH in nli_pertask_linearsearch.py with. Is it the path to KnOTS_model_ckpts/Llama-3-8B/heads.pt ?

**Comment by pratikramesh1** [comment]
Thanks for showing interest in our work. Yes, it is the path to KnOTS_model_ckpts/Llama-3-8B/heads.pt file.

**Comment by AuroraZengfh** [comment]
Hello, I am also wondering where the file is since there's no file attached to it.

**Comment by gstoica27** [comment]
Hi, you can generate this file by running the merging experiment and defining a path for the file.

**Comment by arghavan-kpm** [comment]
Hi, how can we obtain task-specific heads by ourselves? I want to try this method for tinyllama, but with no task specific head I can't get results of merging.

**Comment by gstoica27** [comment]
Hi, sorry please disregard what I posted above, I got confused with another variable. How are you setting up your experiment for this? The "heads" are the classification layers that you'd have for whatever models you've already trained.
