### ISSUE TITLE
lnoting together e.g. SDXL loras?

### ISSUE THREAD

**Issue by fritol** [gstoica27/KnOTS#3]
Is it possible to out of the box merge loras for stable diffussion?
a code / command example?

**Comment by gstoica27** [comment]
Hi, 

KnOTS is both model & domain agnostic, and is by construction an "out-of-the-box" framework.

While we don't include any studies/code on stable diffusion in our work, it remains an exciting opportunity/direction for future exploration. We've included several detailed READMEs in every applicable directory in this repository though, each detailing how this repo can readily be extended to many new tasks/settings (including stable diffusion).
