### ISSUE TITLE
Reconstruction of original $\Delta Ws$ using SVD components

### ISSUE THREAD

**Issue by danielm1405** [gstoica27/KnOTS#5]
Hi,
I am trying to understand the following part of your paper:

![image](https://github.com/user-attachments/assets/3d448aa2-ed06-48ff-9fdb-f8f58f64a915)

You claim that it is possible to recalculate $\Delta W^{(i)}$ as $U \Sigma [V^{(i)}]^T$. I tried to follow the method proposed in your paper to recalculate $Ws$ in this toy example:
```python
import torch

W1 = torch.tensor([[1, 1, 0, -1],
                   [0, 1, 1, 1],
                   [0, 0, 0, 0],
                   [0, 0, 0, 0]], dtype=float)
print(f"{W1.shape=}, {torch.linalg.matrix_rank(W1)=}")

W2 = torch.tensor([[0, 0, 0, 0],
                   [0, 1, -1, 1],
                   [1, 0, 0, 1],
                   [0, 0, 0, 0]], dtype=float)
print(f"{W2.shape=}, {torch.linalg.matrix_rank(W2)=}")

Ws = torch.cat([W1, W2], dim=1)
print(f"{Ws.shape=}, {torch.linalg.matrix_rank(Ws)=}")

U, S, V = torch.linalg.svd(Ws, full_matrices=False)
print(f"{U.shape=}, {S.shape=}, {V.shape=}")

W1_recalc = U @ torch.diag(S) @ V[:,:4].T
print(W1_recalc)
print(f"{torch.allclose(W1, W1_recalc)=}")

W2_recalc = U @ torch.diag(S) @ V[:,4:].T
print(W2_recalc)
print(f"{torch.allclose(W2, W2_recalc)=}")
```

The output I get suggests that $W$ matrix cannot be recalculated in such a way:

```
W1.shape=torch.Size([4, 4]), torch.linalg.matrix_rank(W1)=tensor(2)
W2.shape=torch.Size([4, 4]), torch.linalg.matrix_rank(W2)=tensor(2)
Ws.shape=torch.Size([4, 8]), torch.linalg.matrix_rank(Ws)=tensor(3)
U.shape=torch.Size([4, 4]), S.shape=torch.Size([4]), V.shape=torch.Size([4, 8])
tensor([[ 0.6750,  1.0000, -0.2996, -0.2038],
        [-0.1189,  1.4032,  0.0528,  1.8380],
        [ 0.5038,  0.3312, -0.2236,  0.1622],
        [ 0.0000,  0.0000,  0.0000,  0.0000]], dtype=torch.float64)
torch.allclose(W1, W1_recalc)=False
tensor([[ 0.6750,  0.0000, -0.2996, -0.2056],
        [ 0.3425,  0.0000,  1.7282,  0.1081],
        [-0.4510,  0.0000,  0.6440,  0.1875],
        [ 0.0000,  0.0000,  0.0000,  0.0000]], dtype=torch.float64)
torch.allclose(W2, W2_recalc)=False
```

Please, correct me if the code is wrong. However, as far as I understand, we cannot simply slice $V$ matrix to obtain $V^{(i)}$ matrices that correspond to the i-th task. Therefore, $V^{(i)}$ is not a task-specific matrix and merging ${V^{(i)}}$ matrices does not correspond to merging ${\Delta W^{(i)}}$. I would appreciate a detailed explanation. Thanks in advance.

**Comment by pratikramesh1** [comment]
Hi @danielm1405, thanks for reaching out to us. The pytorch SVD function torch.linalg.svd(Ws, full_matrices=False) return a V matrix which is already transposed.

Hence you can reconstruct the original weights by recomputing without the V.T i.e.
W1_recalc = U @ torch.diag(S) @ V[:,:4]
W2_recalc = U @ torch.diag(S) @ V[:,4:]

Hope you found this useful, if you have any further questions do let us know.

**Comment by danielm1405** [comment]
Everything is clear now. Thanks for the quick response and explanation, this is a very neat idea!
