### ISSUE TITLE
vision datasets heads

### ISSUE THREAD

**Issue by arghavan-kpm** [gstoica27/KnOTS#7]
Hi. In 8vision_training.py, we need to get clip encodings for each dataset by loading that dataset's specific head from HEAD_DIR/VIT_ARCH/dataset_name_head.pt. Would you advise how we should obtain these task specific heads? Thanks.

**Comment by gstoica27** [comment]
Hi, 

Just to understand better, are you asking about how to use this [file](https://github.com/gstoica27/KnOTS/blob/main/dataset/parsing/generate_clip_heads.py)? (found from following the "Datasets" [README](https://github.com/gstoica27/KnOTS/tree/main/dataset)? 


If so, you should be able to generate the heads by running that file, and specifying the datasets you wish to generate heads from [here](https://github.com/gstoica27/KnOTS/blob/main/configs/8vision_train.py). 

I hope this helps! Please let us know if there is anything :).

**Comment by gstoica27** [comment]
Closing due to poster acknowledgment. Please reopen if there are issues :).
